name: CI workflow 

on:
  push:
    branches: [master, dev]


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: mysql_pw
          MYSQL_DATABASE: dmtime_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      DMTIME_DB_USER: "root"
      DMTIME_DB_PW: "mysql_pw"
      DMTIME_DB_URI: "127.0.0.1:3306/dmtime_test"
      DMTIME_JWT_KEY: "testKey"
      DMTIME_IMAGE_STORAGE: "/dmtime/images"
      DMTIME_SERVER_NAME: "localhost:8080"

    steps:
      - uses: actions/checkout@v2
      
      - name: Make image storage directory
        run: |
          sudo mkdir -p $DMTIME_IMAGE_STORAGE
          sudo chmod 777 $DMTIME_IMAGE_STORAGE

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run test
        run: |
          pytest
  
  docker_build_push:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: myorg/myrepository
          tags: latest



